### ISSUE TITLE
Tests do not work when using remote WebDriver 

### ISSUE THREAD

**Issue by bowlej** [westy/pyseext#2]
We have been trying to use these new libs in our current tests, they work fine when run locally but when we try and run them using the remote webdriver on our selenium grid they consistently fall over. Not sure what is causing this but our tests that just use the native selenium methods and wrappers around them do work when using remote WebDriver.

**Comment by westy** [comment]
This should now be resolved.
I made some changes when running remotely.

It was due to the large amount of latency when going through the grid to the system under test. This latency made it pointless waiting for some events from the UI, since by the time the desire to wait for an event had reached the server running the browser, the event had long since happened.
There were a few other tweaks to do with how certain controls, like comboboxes, are interacted with.

So, should all be good.
Closing.
